name: dbsp_drp
channels:
- conda-forge
- defaults
dependencies:
- python >= 3.8
- numpy >= 1.16.0
- astropy >= 4.0
- scipy >= 1.4
- matplotlib >=3.1,<3.5
- pyside2 >= 5.12
- pypeit == 1.6.0
- pytest >= 3.0.7
- yattag >= 1.13
- tqdm >= 4.52
- configobj >= 5
