name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
      fail-fast: false
    # okay to fail if:
    #   on == push && branch != main
    #   OR
    #   on == pull_request && target != main
    continue-on-error: ${{ ((github.event_name == 'push') && (github.ref != 'refs/heads/main')) || ((github.event_name == 'pull_request') && (github.base_ref != 'refs/heads/main')) }}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: dbsp_drp
          python-version: ${{ matrix.python-version }}
          channel-priority: strict

      - run: |
          conda info
          conda config --show-sources
          conda config --show

      - name: Install DBSP_DRP
        run: |
          pip install -e .
          conda list
          pip list

      - name: Testing with pytest
        run: |
          pytest

  test_dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
      fail-fast: false
    # okay to fail if:
    #   on == push && branch == main
    #   OR
    #   on == pull_request && target == main
    continue-on-error: ${{ ((github.event_name == 'push') && (github.ref == 'refs/heads/main')) || ((github.event_name == 'pull_request') && (github.base_ref == 'refs/heads/main')) }}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: dbsp_drp
          python-version: ${{ matrix.python-version }}
          channel-priority: strict

      - run: |
          conda info
          conda config --show-sources
          conda config --show
          conda remove --force pypeit
          conda install pip
          pip install git+https://github.com/pypeit/pypeit.git@1.4.2#egg=pypeit

      - name: Install DBSP_DRP
        run: |
          pip install -e .
          conda list
          pip list

      - name: Testing with pytest
        run: |
          pytest
